### ISSUE TITLE
hi tested you bot on normal adidas site but may problem is with captcha dont load on dev.adidas.com but works on dev.adidas.it(changed the link)..the bot carted on test but dont know where to find the cart hihi

### ISSUE THREAD

**Issue by magboo** [kdcz/3s_atc#1]

**Comment by kdcz** [comment]
1.The captcha box didnt show up or it throw an error ?
2.Login to your account and check your cart

**Comment by magboo** [comment]
solved the issue ty..
by the way i want to use this on adidas.it do i have to use an italian proxy aswell??

**Comment by magboo** [comment]
how can i delete the previous task?? having trouble deleting it

**Comment by kdcz** [comment]
If you want to use the 'splash mode' and cart on adidas.it, yeah it would be better if you use italians proxies. To delete a profile select it and press Delete on your keyboard

**Comment by magboo** [comment]
do you know where i can get an italian proxies really having trouble finding servers?? .by the way do you have any group twitter or slack to share if we succeed i also want to help the community .ty

**Comment by kdcz** [comment]
http://reddit.com/r/adidasatc everything happens here mate, no twitter or chats.

For proxies, I don't know mate you can try here : http://freeproxylists.net/ (select Italia in the country list) 
If the proxy doesn't works the proxy's status will be 'Error'

**Comment by magboo** [comment]
ok mate ty very much really appreciate your work..

**Comment by kdcz** [comment]
Thank you for using it ;)
