### ISSUE TITLE
Error!

### ISSUE THREAD

**Issue by JxNxTHxNL** [kdcz/3s_atc#10]
I am getting a size error, not sure why. Was working before new update.

Also!! Love the bot and everything about it, thank you so much for what you are doing. ![error](https://cloud.githubusercontent.com/assets/25885373/23105597/c120957c-f6af-11e6-9713-6f97dfea7fa2.PNG)

**Comment by kdcz** [comment]
This is a known issue, it will be fixed for the Zebras, I'll keep you informed about the updates

**Comment by JxNxTHxNL** [comment]
Thank you sir!!
