### ISSUE TITLE
Guest checkout

### ISSUE THREAD

**Issue by CashHash123** [kdcz/3s_atc#11]
Is there anyway to add a guest checkout process?

Thanks

**Comment by pfcpinto** [comment]
Use a account generator to auto-create Adidas accounts https://github.com/simmycop/Adidas-Account-Gen this works great and is very easy to use

**Comment by jalex1** [comment]
@pfcpinto does having more accounts mean you can cop more? Thinking for the yeezy release? Sorry if thats a stupid question

**Comment by kdcz** [comment]
It will be done but not in time for zebras
