### ISSUE TITLE
Error adding to cart

### ISSUE THREAD

**Issue by CashHash123** [kdcz/3s_atc#12]
I either get an error on the sizes even though sizes are available, or it will say added to cart, yet will not be in accounts cart?

Is there a way to correct this?

Thanks

**Comment by txsneakerhead23** [comment]
i get this error when trying to add a size that is available : {"result":"ERROR","basket":[]}

**Comment by kdcz** [comment]
@CashHash123 this question has been already answered : Ill push a fix as soon as I can 
@txsneakerhead23 this error was given by adidas so it means that you have a wrong sitekey or didn't set one while the product needs one 
Also make sure to check the 'captcha' box if you did put a sitekey

**Comment by txsneakerhead23** [comment]
Oh okay I thought the bot automatically gets the sitekey.I inputed the sitekey and it said solve captcha but when I try to solve captcha the page says This site can’t be reached

**Comment by kdcz** [comment]
please read the instructions on how to install the bot Im done replying to the same questions 
The bot automatically gets the sitekey for splash mode only
