### ISSUE TITLE
 The requested URL /sitekey.php was not found on this server.

### ISSUE THREAD

**Issue by KaryMassiel** [kdcz/3s_atc#13]
Hi!

i continue to receive this message "The requested URL /sitekey.php was not found on this server." on the browser after clicking on the solve captcha. I might have missed a step installing the program but i have no idea what it can be.

any help is gladly appreciated :]

**Comment by jalex1** [comment]
Dude are you using a htdocs folder? You need to install a program like xampp to run the php file like with the nikedestroyer program? Learn how to use that one first and youtube the tutorials on it

**Comment by KaryMassiel** [comment]
Oh okay. i was confused because it said install WAMP didn't know they were related. Thanks.

**Comment by kdcz** [comment]
@jalex1 THANKS
