### ISSUE TITLE
Captcha issues

### ISSUE THREAD

**Issue by edeword** [kdcz/3s_atc#14]
overtime I solve a captcha it takes me to a new one and can never actually solve the captcha pls help

**Comment by kdcz** [comment]
Whaaaat ?

**Comment by txsneakerhead23** [comment]
I think what he means is when it says SOLVE CAPTCHA NOW and he trys solving it nothing happens it justs keeps refreshing to solve again thats whats happening with me.

**Comment by CashHash123** [comment]
What he is referring to is that delayed captcha where images take long to populate and after waiting and solving captcha still throws error, 
I believe is what he is referring to

**Comment by txsneakerhead23** [comment]
this is the issue im getting https://vid.me/RaQd

**Comment by kdcz** [comment]
Oh okay I see now,did you put the right path for your htdocs folder ?
Do you have a file called "recaptcha_response" in your /htdocs/ folder ?

**Comment by txsneakerhead23** [comment]
that was my problem i didn't update the path thanks and its called slippery-migos from their new album

**Comment by edeword** [comment]
where is recaptcha_response located?

**Comment by kdcz** [comment]
@txsneakerhead23  np enjoy the bot
@edeword  it doesn't matters, you dont need it
