### ISSUE TITLE
about wrong sitekey

### ISSUE THREAD

**Issue by junine1210** [kdcz/3s_atc#15]
Hello.
Thank you for making a good script.
I'm on the tests.
but it seems to bring up the wrong sitekey.
Did I set something wrong?

![1](https://cloud.githubusercontent.com/assets/22272754/23165335/eda58212-f87e-11e6-938e-0a580b5eeb0c.JPG)
![2](https://cloud.githubusercontent.com/assets/22272754/23165336/edb628d8-f87e-11e6-97d1-d3baee217940.JPG)
![3](https://cloud.githubusercontent.com/assets/22272754/23165337/eddd7618-f87e-11e6-89d1-8d6cd106253b.JPG)

**Comment by kdcz** [comment]
No its okay just solve the captcha now lol 
Right click and click " solve captcha"

**Comment by junine1210** [comment]
The sitekey is not correct, so an error occurs.

But when I insert the sitekey extracted from the product page, it works fine.

**Comment by junine1210** [comment]
'Invalid captcha' error

**Comment by kdcz** [comment]
Oh okay sorry yeah it is normal but why set splash page mode when its not necessary ?

**Comment by junine1210** [comment]
I was just testing for zebra :)
I wonder where the wrong sitekey was extracted.

**Comment by kdcz** [comment]
From the test website I created lol I put the first sitekey I found

**Comment by junine1210** [comment]
Okay.
Thank you so much for your kindness.
Have a nice day.

**Comment by kdcz** [comment]
Thank you for your feedback,have a nice day too
