### ISSUE TITLE
captcha 

### ISSUE THREAD

**Issue by jeremycwu** [kdcz/3s_atc#17]
Hi, I'm super noob at this so I'm sorry for probably wasting your time.

1. Where do I put the php file? I can't find the /www/ folder on my windows..
2. I saw that there's a splash test page but couldn't find it in the markdown, could I get the link?

I'll probably have more questions but I wanted to make sure I installed it properly.
Thank you so much!

**Comment by jalex1** [comment]
Search how to install nike destroyers php for windows, then using the htdocs folder put it in there. Doesn't work on mac

**Comment by jeremycwu** [comment]
thanks for your reply, I installed xampp and put the php into htdocs but it just says connecting without any change after 10 minutes. Could you specify the settings on a regular, non-splash adidas product that does not have captcha vs a regular, non-splash adidas product that DOES have captcha?
