### ISSUE TITLE
For the upcoming V2 release...

### ISSUE THREAD

**Issue by JxNxTHxNL** [kdcz/3s_atc#18]
Should we run as "Splash Mode" or if we have all the info, just run regularly??

Thank you again so much for this, love the bot. Works flawlessly for me.

**Comment by joeymickss** [comment]
they use splash for yeezys and other limited releases. Usually its up way before the shoe can even ATC so ,your most likely going to use splash mode. But you never know with adc.

**Comment by JxNxTHxNL** [comment]
i know that.... that wasn't the premises of my comment though. thanks.

**Comment by joeymickss** [comment]
ah my bad

**Comment by kdcz** [comment]
If you have all the info run regularly but it won't work on yeezys because you need HMAC cookie

**Comment by JxNxTHxNL** [comment]
so should i run splash mode?

**Comment by kdcz** [comment]
I said it like maybe 3 times already and it is written in the instructions : YES USE SPLASH MODE ON YEEZYS

**Comment by JxNxTHxNL** [comment]
ok im sorry :(
