### ISSUE TITLE
Logging In Stuck

### ISSUE THREAD

**Issue by aagulto** [kdcz/3s_atc#2]
I'm still stuck with logging in even  with the updated version. Please help!

**Comment by kdcz** [comment]
Which country

**Comment by aagulto** [comment]
U.S

**Comment by kdcz** [comment]
Pushed an update, can you try again please thank you

**Comment by aagulto** [comment]
It works like a charm! Thank you so much for fixing it. Hopefully this one will work on Zebra release :-). If you need a tester, I'm more than happy to help. But just wanted to give you a heads up, I don't do codes stuff okay? LOL.

**Comment by kdcz** [comment]
Nice ! Thank you for reporting the issue and I will improve the program for the Zebra release don't worry ;)
PM me on reddit so I know your username if I need a tester ;)

**Comment by aagulto** [comment]
PM sent!

**Comment by aagulto** [comment]
Would it be possible to make the profile's Size, Sitekey, Client ID, Duplicate, etc editable, instead of doing it manually if there's a typos?

**Comment by kdcz** [comment]
Yeah it's already planned don't worry ;)
Considering this issue solved, closed.
