### ISSUE TITLE
How do I match the number of proxies and adidas accounts?

### ISSUE THREAD

**Issue by junine1210** [kdcz/3s_atc#22]
How do I match the number of proxies and adidas accounts?

1 proxy per 1 acconut?

**Comment by kdcz** [comment]
If you had read the instructions, you would have seen that once a proxy has reached the product page it will cart for all profiles

**Comment by junine1210** [comment]
Thank you for your reply.
It's better than I expected.
Thanks again. For making good scripts. Have a nice day.
