### ISSUE TITLE
Setting it up on a Mac.

### ISSUE THREAD

**Issue by jacobshay** [kdcz/3s_atc#24]
Hey anyway someone could help me set this up on mac. Im having a little bit of trouble.

**Comment by OGProgrammer** [comment]
So this is a C# implementation , I downloaded the .NET Mac Framework and Mono but haven't bothered trying to see if this will open/compile in it. You can go ahead and try if you'd like.

**Comment by kdcz** [comment]
There is no support for Mac atm, I suggest you to download a Virtual Box and run the program in it
