### ISSUE TITLE
Sitekey not found issue

### ISSUE THREAD

**Issue by Vextraaa** [kdcz/3s_atc#25]
Hello! I have setup the bot but I can't get the sitekey.php to work, I have the file located in C:\wamp64\www as sitekey.php I'm really not too sure on what could be causing the issue as I have put 127.0.0.1 dev.adidas.com in the Windows hosts file. If anyone can help me it would be highly appreciated. 

Also would anyone possibly know what this error means? 
"- myemail@gmail.com - BA8278: {"result":"ERROR","basket":[]}"

**Comment by Vextraaa** [comment]
Also would anyone possibly know what this error means? 
"- myemail@gmail.com - BA8278: {"result":"ERROR","basket":[]}"

**Comment by kdcz** [comment]
"{"result":"ERROR","basket":[]}" usually means that you didn't solve the captcha
Sitekey.php is a php file to show the recaptcha api with the associated data sitekey, just put the sitekey in your profile then check the "captcha" box and when the program asks you to solve captcha, right click on the profile and press Solve Captcha
