### ISSUE TITLE
Some Missing Features

### ISSUE THREAD

**Issue by theCoder44** [kdcz/3s_atc#26]
Hi,

Here are some ideas for missing Features.

- Splash Page Config
Make the CssSelector which is used to identify splash page configurable in order to avoid a new program Version if adidas will change his site. 
Before it was: ".message.message-1.hidden" then: "sk-fading-circle"

/*By.CssSelector(".message.message-1.hidden")*/By.ClassName("sk-fading-circle"

-Task Scheduler
You start an uncontrolled Task for each Profile. Use Backgrouldworkers:
https://msdn.microsoft.com/de-de/library/system.componentmodel.backgroundworker(v=vs.110).aspx
Add the possibility to stop/run each Profile individually instead of "run all".
Use Log4net for a logfile per thread: https://logging.apache.org/log4net/

**Comment by kdcz** [comment]
Thank you for your suggestions,will do my best to implement that except the log thing because I don't find it necessary atm

**Comment by theCoder44** [comment]
Do you think that there is a possibility to remove the PHP dependency ?
It is annoying to run an Apache + PHB.

There Exits integrated Browsers for c# like CefSharp: https://github.com/cefsharp/CefSharp
The PHP stuff could be done with Javascript or something ?
e.g.: Create a temporary HTML file for the captcha and open in the the app with CefSharp.

**Comment by kdcz** [comment]
Not possible because you need to be dev.adidas.com else the captcha box will throw an error and Ill make the captchas solving so you can keep one tab for all captchas which is way faster than integrating browsers

**Comment by theCoder44** [comment]
:)
