### ISSUE TITLE
Splash Page - country based proxies

### ISSUE THREAD

**Issue by Universalx182x** [kdcz/3s_atc#27]
Hello,

in case of Proxy use, does the bot redirects you to the country based splash page (yeezy, wang,...), or is there a way to use EU proxies (DE, UK,...) for smaller countries too?

The issue I have is, that proxies are very rare in some specified countries as austria for example.

TY

**Comment by theCoder44** [comment]
Basically it depends how adidas's geolocation work on server side, which redirects you on another locale (domain).

- Accept-Language Header
Only the driver profile needs to be changed in this case. Any IP address can be used.

FirefoxProfile profile = new FirefoxProfile();
profile.setPreference("intl.accept_languages", formatLocale(locale));
... 

- IP Geolocation
Locale dependent IP is needed. e.g.: if you want access adidas.at/splash you will need an AT IP address (proxy).

- HTML5 Geolocation
More complex, but basically same as above.

- Additional context filering

  *IP-Blacklist
   IP or proxy can be banned.

  *Subnet filtering
   Only 1st-Level proxies would work.   

  ...

**Comment by kdcz** [comment]
Well It really depends,sometimes I could access Australia splash with an european ip but I suggest you to use sessions as they work much better atm than proxies,btw most of known proxies were banned by adidas

**Comment by Universalx182x** [comment]
So I should run several sessions with the same IP?
Won't adidas ban my IP in that case due to entering several times with the same adress?

TY

**Comment by kdcz** [comment]
Nope because then they will have to ban large networks like universites,internet cafes,public wifis...

**Comment by jalex1** [comment]
How can they tell when its a proxy vs a real ip adress?

**Comment by kdcz** [comment]
Maybe they are using a service from specialized company that has a huge blacklist ? I guess its this but Im not really into Web coding so can't really tell you how it exactly works

**Comment by theCoder44** [comment]
@jalex1 
A Proxy has a real IP-address. Proxy addresses (including subnets) are known after some time and end up on blacklists.

@kdcz 
Does run your app without a Proxy ?

**Comment by theCoder44** [comment]
Recommended setup:

setup multiple virtual machines
each virtual machine uses a different internet connection
for instance use LTE or HSDPA dongles
additionaly you can rotate the dongle IP's by force reconnects

**Comment by jalex1** [comment]
@theCoder44  what is the advantages of setting up in that way?

**Comment by OGProgrammer** [comment]
Just FYI, I have a hunch they are using this list http://www.ip2location.com/databases/db24-ip-country-region-city-latitude-longitude-zipcode-timezone-isp-domain-netspeed-areacode-weather-mobile-elevation-usagetype

usage_type can flag something as a "cloud ip" versus a residential ip.

**Comment by kdcz** [comment]
@theCoder44 it will work only if you have a static ip, and (I think?) that most of the people have a fixed ip.

**Comment by Universalx182x** [comment]
If you have multiple accounts running with sessions, doesn't adidas cancel your orders due to the same IP if you get more than one pair?

This is known, so any suggestions to avoid cancellation?

**Comment by kdcz** [comment]
Connecting to your account with a different device/proxy/VPN each time would maybe work.

**Comment by Universalx182x** [comment]
Sounds good, thx!
