### ISSUE TITLE
Cannot Log In

### ISSUE THREAD

**Issue by herbertwells** [kdcz/3s_atc#29]
Hi, I'm stuck on logging in. AU locale. Any help would be greatly appreciated. 
![capture](https://cloud.githubusercontent.com/assets/12973934/24645510/c1b68720-195b-11e7-8555-eb0b2633e746.PNG)

**Comment by Universalx182x** [comment]
Did you delete profile and added again?
That worked for me

**Comment by herbertwells** [comment]
Yes, a few times. I was able to login on AdidasUS but not AU

**Comment by Universalx182x** [comment]
Strange, might be a regional problem in the code. 
I can try to log in at AU when Im at home.

Did you try already captcha? If yes, does it work?

**Comment by herbertwells** [comment]
No I haven't tried captcha. I was just trying to test adding a shoe to cart which didn't have a captcha.

**Comment by Universalx182x** [comment]
Ok, let me know when you test it, thats where i stuck.

**Comment by Universalx182x** [comment]
log in fails on australia, also on other sites.

Might be possible that adidas changed something and the bot needs to be updated?

**Comment by jalex1** [comment]
@kdcz Having the same issue here with logging onto the uk site?

**Comment by kdcz** [comment]
Sorry guys I've been pretty busy these days, I still don't have much time but I'm going to work on the bot on my free time to make it ready for the Cream Whites V2.

**Comment by kdcz** [comment]
fixed : https://github.com/kdcz/3s_atc/commit/ff13420d74c1cf204a9626b4ea1fb626e37d7a12

**Comment by jalex1** [comment]
yep  working again! thanks
