### ISSUE TITLE
please help me login error

### ISSUE THREAD

**Issue by top1st** [kdcz/3s_atc#30]
ERROR:render_process_host_impl.cc(2094)] Request for unknown Channel-associated interface: device::mojom::ScreenOrientationListener
//driverService.HideCommandPromptWindow = true;
i added comment above. please help me.
![untitled](https://cloud.githubusercontent.com/assets/23559697/25493929/80948128-2baa-11e7-9fb8-05063a32d7d4.png)
it take too long time when logining and i got error timeout.
![recommend](https://cloud.githubusercontent.com/assets/23559697/25494346/f16bed40-2bab-11e7-8fe7-de1f2aac83d6.png)

**Comment by kdcz** [comment]
If it takes too long then it's because of your internet connection I guess because it's working fine on my side

**Comment by jalex1** [comment]
Bot dis not work on uk release, all sessions just said setting up then after a while error. Managed to cop manually though

**Comment by kdcz** [comment]
Yeah saw that ,managed to cop 3pairs with the bot by changing the browser to chromedriver for sessions going to push an update soon, seems like adidas blocked headless browsers

**Comment by jalex1** [comment]
Okay great, did you get my message on reddit?

**Comment by top1st** [comment]
okay, when i changed my ip to us it works, could you help me how i can get correct client id please

![image](https://cloud.githubusercontent.com/assets/23559697/25564685/7b8f0250-2deb-11e7-9fb8-df030e2065b4.png)

**Comment by top1st** [comment]
![image](https://cloud.githubusercontent.com/assets/23559697/25564715/ba798a26-2deb-11e7-85d8-382c83c3d35e.png)

**Comment by kdcz** [comment]
Just tested inventory checking on BA7208 on US website and it works fine for me ...
