### ISSUE TITLE
unable to login

### ISSUE THREAD

**Issue by felixthechef** [kdcz/3s_atc#32]
the AU login seems to be broken again :( any chance for a fix?
much love x

**Comment by kdcz** [comment]
I'll check that!

**Comment by jalex1** [comment]
Unrelated, but what do you think the chances are of getting ip banned when using multi-sessions?

**Comment by kdcz** [comment]
No idea, but if you open a moderate number of sessions it should be fine. But I don't think that it's a permanent ban : I already got banned once(not for using multi-sessions, but because I tried to access a "protected" ressource) and I was able to access the website again 2 weeks after.

**Comment by jalex1** [comment]
Okay, for releases, is it likely that i would get banned immediately or after the release?

**Comment by kdcz** [comment]
Immediately

**Comment by felixthechef** [comment]
The chrome window is opening to login, but gets stuck on the spinning wheel. The details are correct but it's just not getting through. I am able to login on the other locale's so I believe it's an AU specific issue.

**Comment by felixthechef** [comment]
keep up the good work by the way, I'm sure everyone appreciates what you're doing <3

**Comment by kdcz** [comment]
I'll see what I can do!

**Comment by kdcz** [comment]
Check the new update and see if it's solved.
