### ISSUE TITLE
Calabasas pants

### ISSUE THREAD

**Issue by jeffreykwon44** [kdcz/3s_atc#34]
Do you guys update it for the calabasas pants dropping this weekend?

**Comment by kdcz** [comment]
I will try to push an update by sunday

**Comment by jeffreykwon44** [comment]
can you make a video on how to install and setup for calabasas pants? It's
confusing

**Comment by kdcz** [comment]
I pushed a new update for the calabasas release, there will be 2 splash page so put the right one.
Red pants SKU: CV7905 
Black pants SKU: CV8357

@jeffreykwon44 Run 3s_atc.exe in the /Release/ folder : 
-If you want more than one product : create 1 profile per product,put the product ID,your adidas email and password, the pants size, check the 'Splash' box and click add. Then put the splash mode on 'multi sessions', enter how many sessions you want(don't put 20 if you have a bad cpu), enter the splash url and click Login and when it's logged in and the splash page is live press Run.
-If you want only one product : put the splash mode on 'multi sessions', enter how many sessions you want, enter the splash url and click Run guest mode, then you can show the browser by right clicking on the session and pressing 'Show' and cop manually.

Please note that it's the first time that there will be a splash page for pants so idk if the automated process will work.
