### ISSUE TITLE
Install help

### ISSUE THREAD

**Issue by jmconste** [kdcz/3s_atc#35]
I need help installing this, because I have a mac, and I see its ran with .exe so I wonder if you guys do support mac

**Comment by kdcz** [comment]
There is no support for Mac yet, you can use a VirtualBox to run it

**Comment by jmconste** [comment]
I am kind of lost on how to install it on virtual box, can I kindly ask if you can show me how

**Comment by kdcz** [comment]
Well look on youtube on how to install it then simply switch to windows, download 3s_atc and run it.
Btw I will start working on a MAC version in the upcoming months and *should* be out by the end of the year
