### ISSUE TITLE
BLOCKED ON CHECKING SIZES

### ISSUE THREAD

**Issue by Blazayy** [kdcz/3s_atc#36]
Hi, 

Thanks for your project ! 

I'm testing it right now, but when I solve captcha it seems that the program block on checking sizes and nothing happen then ... 

Any idea why I have this Issue ? 

Thanks

**Comment by kdcz** [comment]
Can you tell me the product ID,the product link and your locale please ?

**Comment by Blazayy** [comment]
Product ID : BY3011
Link : https://m.adidas.fr/chaussure-nmd_c2/BY3011.html
Locale : FR

Will you update your program for future yeezy drop ?

Thanks for your reply and your work !

Kind regards

Envoyé de mon iPhone

Le 29 oct. 2017 à 12:27, kdcz <notifications@github.com<mailto:notifications@github.com>> a écrit :


Can you tell me the product ID,the product link and your locale please ?

**Comment by kdcz** [comment]
Thank you for the report, I'll push a fix tomorrow.

**Comment by Blazayy** [comment]
Okay cool. Thanks a lot for the fix ! Do you have a direct email or skype where we can chat directly ? If I don't want to drop it on github, email me at kevin.carra@hotmail.fr :)


________________________________
De : kdcz <notifications@github.com>
Envoyé : dimanche 29 octobre 2017 19:10
À : kdcz/3s_atc
Cc : Blazayy; Author
Objet : Re: [kdcz/3s_atc] BLOCKED ON CHECKING SIZES (#36)


Thank you for the report, I'll push a fix tomorrow.

**Comment by kdcz** [comment]
k0d0c0z0@gmail.com

**Comment by kdcz** [comment]
Update : -No more logging in, it's useless and faster without it
-Instead of your email/pw just put a name for the profile
-Size checking and adding to cart fixed
