### ISSUE TITLE
Basket Error

### ISSUE THREAD

**Issue by felixthechef** [kdcz/3s_atc#38]
![error](https://user-images.githubusercontent.com/26131447/32318901-c91209b0-c00c-11e7-9d7a-d3fd1480db53.JPG)

I believe there's an error when adding a product to the basket. Maybe adidas has changed something in the back?

**Comment by kdcz** [comment]
Was there a captcha ? 
Btw just pushed a new update

**Comment by felixthechef** [comment]
It was after the captcha had been solved, however after your newest update it's working a breeze! 

keep up the amazing work legend

**Comment by kdcz** [comment]
Good to hear that and thanks for the support!
