### ISSUE TITLE
Won't Add To Cart?

### ISSUE THREAD

**Issue by shawngaetano** [kdcz/3s_atc#39]
I had tested the program a few nights ago before you updated and it worked fine, but now when I click run nothing happens. Everything seems to be correct on my end?

**Comment by kdcz** [comment]
Like literally nothing happens ?

**Comment by kdcz** [comment]
You're not stuck on a specific status ?

**Comment by shawngaetano** [comment]
Yea like I’ll hit run and nothing happens and the status just stays blank. I also tried to check inventory and the same thing as well it just is an endless message of “Checking inventory for (product ID) and nothing ever comes up.

**Comment by kdcz** [comment]
Can you post a screenshot of the folder from which you launch the program ?

**Comment by shawngaetano** [comment]
Are you referring to the entire folder, or just the release folder? Here is a screencap of the release folder.
![3satcfiles](https://user-images.githubusercontent.com/33476593/32566353-a407e7ca-c485-11e7-911d-f6cad98ec593.png)

**Comment by shawngaetano** [comment]
Tried deleting and redownloading also to no avail.

**Comment by kdcz** [comment]
Can you try to open 3s_atc browser and tell me if the browser opens ?

**Comment by shawngaetano** [comment]
![3satcfiles1](https://user-images.githubusercontent.com/33476593/32585899-b1043864-c4cd-11e7-812b-62a284c0e575.png)

**Comment by shawngaetano** [comment]
Wait a second I think I fixed the issue. I have the 3s_ATC.exe copy file on my desktop standing alone, and when I run it, it doesn't work, however when I run it from directly from the folder with all the files it works fine. Pretty sure that's the reason it wasn't working.

**Comment by kdcz** [comment]
Yes you must run it from the folder else it won't work...
You can make a shortcut and put it on your desktop if you want.
