### ISSUE TITLE
Cart with browser: Chrome error

### ISSUE THREAD

**Issue by xdmod2** [kdcz/3s_atc#41]
Getting some BW1126 error, please see the attached screenshot
![capture2](https://user-images.githubusercontent.com/20647076/32690139-61b28394-c6bf-11e7-9c68-543fc21cfec0.PNG)
.

**Comment by xdmod2** [comment]
Quick update: After entering the Sitekey seems it's working. However, the captcha is extremely slow.

**Comment by kdcz** [comment]
Yes this error occurs when the product needs a captcha response, I know the captcha is extremely slow because of the "dev.adidas.com" domain, I'll try my best to fix that and will add 2captcha support aswell.

**Comment by kdcz** [comment]
Should be fixed with recent update
