### ISSUE TITLE
Pipe is broken?

### ISSUE THREAD

**Issue by shawngaetano** [kdcz/3s_atc#42]
![pipeisbroken](https://user-images.githubusercontent.com/33476593/32690652-f0664a5a-c6c7-11e7-93cb-602bda81536a.png)

Was really hype about possibly copping the new Pharrell HU NMD but I got this error when they dropped :/

**Comment by kdcz** [comment]
Never happenned to me, can you please repeat the process again with a random product and tell me if the error stil occurs ? thank you

**Comment by shawngaetano** [comment]
INteresting. It works fine with other products. I am guessing that Adidas is cracking down on bots. Do you think it will work for the next yeezy release?

**Comment by kdcz** [comment]
It should yeah
