### ISSUE TITLE
No issue, just trying to get involved 

### ISSUE THREAD

**Issue by DMarkz20** [kdcz/3s_atc#47]
Just coming across all of this now, and I'm definitely interested in giving your bot a try for the beluga 2.0! I've tried using BNB AIO for the past couple releases and had 0 luck, total waste of money so far. If I could get some info on the setup so everything goes smooth that'd be great! Cheers

**Comment by kdcz** [comment]
Check the  replies on my post https://www.reddit.com/r/adidasatc/comments/7cw2zz/comment/dpuqvks?st=JADSFIRN&sh=602fc625
