### ISSUE TITLE
Proxy Settings

### ISSUE THREAD

**Issue by jalex1** [kdcz/3s_atc#6]
For using a proxy, where do i put the port number? thanks

**Comment by kdcz** [comment]
Fill the address text box this way : http://address:port

**Comment by jalex1** [comment]
so for 'address' it would be the ip address right?

**Comment by kdcz** [comment]
Yes sir

**Comment by jalex1** [comment]
Can you use this proxy setting for normal cops with no splash page?

**Comment by jalex1** [comment]
and also i saw you need to choose a chrome path, is that to the standard chrome browser or to chromedriver.exe?

**Comment by kdcz** [comment]
For normal cops I don't see why you need a proxy,if you really need one just setup a proxy in windows proxy settings and it should do the trick.

For your second question,I don't use chromedriver no more it was too buggy so choose standard chrome.exe
