### ISSUE TITLE
Question: program workflow

### ISSUE THREAD

**Issue by theCoder44** [kdcz/3s_atc#9]
Hi,

great work so far.
I played a little bit arrount with the program.
When the fields are not filled correctly or are empty the program crashes.
maybe add some exception handling ?
What about to allow to add a non Proxy Profile (use the local IP) ?

- The fields SiteKey, ClientID and Duplicate are not clear for me. Where i get this Information ?
- Can you describe a Little bit the workflow of the program ?
- The bot does not do a checkout, but how the checkout works ?
   I understand it does the splash page stuff and adds it to my Card in Code behind but how can i checkout then ?

**Comment by kdcz** [comment]
There are exception handling, it's weird that this is hapenning, I'll check that
-I don't see the point of using a non proxy profile for splash mode as you can just open your brower and wait until you pass the splash page
-Sitekey, clientID and duplicate : with the splash mode the program wil get them for you
Sitekey : key for recaptcha api, different for each zone(europe/US/Canada/Australia...)
ClientID : client id, different for each zone
Duplicate : duplicate field for the recaptcha form

You can learn more here: https://www.reddit.com/r/adidasatc

-The program add to your cart products without having to be on the product page, this allows you to buy faster popular and limited shoes
Also when the product has a splash page, you can setup how many proxies you want in the proxy list and once one of them has reached the product page, the application will get all the informations and cart the product for all profiles

-Just login on adidas with the email and password, go to your cart and checkout

**Comment by theCoder44** [comment]
That helps me :) Thanks !
